### PR TITLE
Update version to release candidate with fixes

### PR DESCRIPTION
**Pull request by wallento**
Was much easier actually. The release candidate fixed it already, but it doesn't show up as latest version. I can look into fixing it in the 1.8.0-post release cycle, but probably this is a motiviation to get 1.9.0 done asap.

### CODE REVIEW

**Comment by bavovanachte** [comment]
Any idea on when 1.9.0 would actually be released? Would be nicer to have a released version as a dependency than an RC

**Comment by wallento** [comment]
I hope by the end of the week. The changes to upstream wavedrom seem pretty limited and not on the core logic, but the registers. I will make another post release of the current release candidate, because there is a bug in the last post release..

**Comment by wallento** [comment]
We should at least bump to 1.8.0-post3 until the actual features are finished.

**Comment by bavovanachte** [comment]
Ok, fine for me to merge for now with the rc dependency. I'll hold off releasing on pypi until 1.9.0 is released on wavedrompy side

**Pull request merged**
